server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin.sprouts.kr/
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: sprouts-spring-cloud-web-api-jpa
          uri: http://sprouts-spring-cloud-web-api-jpa:8080
          predicates:
            - Path=/framework/api/authorization/**

eureka:
  instance:
     instance-id: ${random.uuid}
     prefer-ip-address: true
     lease-renewal-interval-in-seconds: 3
     lease-expiration-duration-in-seconds: 10
  client:
    client:
      enabled: true
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    disable-delta: false
    service-url:
      defaultZone: http://discovery.framework.sprouts.kr/eureka/

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enable: true
    refresh:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
    gateway:
      enabled: true
  info:
    java:
      enabled: true

sprouts:
  logstash-appender:
    name: LOGSTASH
    identifier: ${spring.application.name}-${spring.profiles.active}
    destinations:
      - host: 127.0.0.1
        port: 5045
