server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always
  cloud:
    discovery:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

eureka:
  client:
    client:
      enabled: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enable: true
    refresh:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
    gateway:
      enabled: true
  info:
    java:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3_MULTI
  zipkin:
    tracing:
      endpoint: "http://zipkin.framework.local/api/v2/spans"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

sprouts:
  logstash-appender:
    name: LOGSTASH
    identifier: ${spring.application.name}-${spring.profiles.active}
    destinations:
      - host: observability.local
        port: 5045
