server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin.devops.sprouts.kr/
  cloud:
    discovery:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

eureka:
  client:
    client:
      enabled: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enable: true
    refresh:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
    gateway:
      enabled: true
  info:
    java:
      enabled: true

sprouts:
  logstash-appender:
    name: LOGSTASH
    identifier: ${spring.application.name}-${spring.profiles.active}
    destinations:
      - host: 192.168.0.100
        port: 5045
