server:
  port: 8761

spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin.sprouts.kr/

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enable: true
    refresh:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always

sprouts:
  logstash-appender:
    name: LOGSTASH
    identifier: ${spring.application.name}-${spring.profiles.active}
    destinations:
      - host: 127.0.0.1
        port: 5045
